### ISSUE TITLE
Laufzeit von npm install auf dem Buildserver

### ISSUE THREAD

**Issue by marcwittke** [PhilippSpo/mep-frontend#17]
Eigentlich eher ne Frage...

Mein VS Online Build, der Frontend und Backend zusammenbaut und auf Azure deployed braucht ungefähr 9 Minuten. 4 Minuten davon belegt ```npm install```. Ist das normal? Kann man da was machen?

(VSOnline bzahlt man nach Minuten ;-) die ersten 240 pro Monat sind aber umsonst)

**Comment by PhilippSpo** [comment]
Auf `yarn` wechseln und `node_modules` cachen

**Comment by PhilippSpo** [comment]
@SMenigat wir sollten support für `yarn` hinzufügen. Das ist glaub ich nur eine file. Dann kann man `yarn install` statt `npm install` machen.

**Comment by marcwittke** [comment]
Ich befürchte für meinen Build bringt das nix, da ich keine eigene VM als Buildworker habe, sondern den Standard Shared Worker hernehme. Und der beginnt immer nackig, d.h. auch ein irgendwie konfigurierter Cache wäre auf dem leer. Das Thema [scheint bei MS auf der Agenda zu sein](https://github.com/Microsoft/vsts-tasks/issues/553), aber bisher gibt es außer einem eigenem Build Worker wohl keine Alternative.

Die Frage ging auch eher in die Richtung: brauchts das alles, was wir da jedes mal restoren? Oder ist das ein großzügiger Rundumschlag vom Codegenerator, mit dem Ihr das aufgesetzt habt, und es wäre mit vertretbarem Aufwand möglich, da das eine oder andere MB einzusparen?

**Comment by marcwittke** [comment]
Update: es sind garnicht die MBs, sondern die Resolution vom Dependency-Tree. Kann man wohl nix machen.

**Comment by PhilippSpo** [comment]
Yarn ist auch beim Resolven der dependencies viel schneller als NPM.
