### ISSUE TITLE
Entscheidung zu UTC und Lokalzeit

### ISSUE THREAD

**Issue by marcwittke** [PhilippSpo/mep-frontend#18]
Wie wollen wir mit lokalen Uhrzeiten umgehen?

gesetzt ist, dass in der DB immer und ausschließlich UTC steht. Aber soll das backend die Verantwortung bekommen, die jeweilige Zeitzone des Clients zu detektieren und eine entsprechende Umrechnung schon auf dieser Ebene vornehmen, oder legen wir diese Verantwortung ins frontend?

Falls das Backend die Verantwortung bekommt, müssten wir dem Client mindestens die Aufgabe verpassen, z.B. einen Header mitzuschicken, in dem die UTC-Abweichung in Minuten steht.

**Comment by marcwittke** [comment]
dotnet spuckt übrigens ohne weiteres gefrickele Dates etwas eigensinnig ins JSON. Da könnte [sowas hier](https://www.npmjs.com/package/json-dotnet-date) interessant werden

**Comment by PhilippSpo** [comment]
Ich würde im frontend das ganze schon in UTC umwandeln und auf dem Server nur UTC dates akzeptieren.

**Comment by marcwittke** [comment]
> Ich würde im frontend das ganze schon in UTC umwandeln 

gekauft.
