### ISSUE TITLE
Errorhandling

### ISSUE THREAD

**Issue by janbreddin** [PhilippSpo/mep-frontend#32]
In https://github.com/PhilippSpo/mep-backend/pull/23 haben wir die Diskussion, ob uns die normalen HTTP-Fehlercodes reichen, da der Client so gestrickt ist, dass sie nicht auftreten oder ob serverseitige Fehlermeldungen vom Client angezeigt werden können/sollen. Wenn ja - wie stellt ihr euch das vor? Wäre gut, wenn wir das bald klären, damit wie die Nachrichten im Server auch entsprechend internationalisieren.

**Comment by marcwittke** [comment]
Ich habs ziemlich parallel auch im backend aufgemacht: https://github.com/PhilippSpo/mep-backend/issues/25
